/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ruknocker_services_KnockerService */

#ifndef _Included_com_ruknocker_services_KnockerService
#define _Included_com_ruknocker_services_KnockerService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ruknocker_services_KnockerService
 * Method:    knock
 * Signature: (Ljava/lang/String;SI)V
 */
JNIEXPORT void JNICALL Java_com_ruknocker_services_KnockerService_knock
  (JNIEnv *, jobject, jstring, jshort, jint);

#ifdef __cplusplus
}
#endif
#endif
